version: '3.0'
services:  
  api-1:
    build: 
      dockerfile: ./python1.dockerfile
      context: .
    image: tmtm/api1
    container_name: api-teste1
    ports:
      - "5020:5020"
    networks: 
      - api-teste
  
  api-2:
    build: 
      dockerfile: ./python2.dockerfile
      context: .
    image: tmtm/api2
    container_name: api-teste2
    ports:
      - "5021:5021"
    networks: 
      - api-teste

networks:
  api-network:
    driver: bridge